name: deploy-pg-api

on:
  push:
    branches: ["master"]

jobs:
  deploy-pg-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Crear archivo .env con la variable de conexión a la base de datos
      - name: Configurar archivo .env
        run: |
          touch .env
          echo "DEV_DATABASE_URL=${{ secrets.PG_CONN }}" >> .env
          cat .env

      # Construir imagen Docker
      - name: Construir imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/pg-restapi:${{ github.sha }} .

      # Verificar credenciales de Docker
      - name: 🚨 Verificar credenciales de Docker
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ] || [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "Error: Las credenciales DOCKER_USERNAME o DOCKER_PASSWORD no están configuradas."
            exit 1
          fi

      # Iniciar sesión en Docker Hub
      - name: 🔑 Iniciar sesión en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Subir imagen a Docker Hub
      - name: 🚀 Sub](#)
