name: deploy-pg-api

on:
  push:
    branches: ["master"]

jobs:
  deploy-pg-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: echo 'hello world ...'
      - run: ls -la
      - run: touch .env
      - run: echo "DEV_DATABASE_URL=${{ secrets.PG_CONN }}" >> .env
      - run: cat .env

      - run: docker build -t adsoft/pg-restapi:${{ github.sha }} .
      - run: docker images

      - name: 🔑 Iniciar sesión en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 🚀 Subir imagen a Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/pg-restapi:${{ github.sha }}
